# -*- coding: utf-8 -*-
"""ceasar_cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwZ2B6griBOkCmvvwnl9ZXQj8c2v01BO
"""

lower = 'abcdefghijklmnopqrstuvwxyz'
upper = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

pt=input("enter pt:")
key=int(input("enter key:"))
ct = ''
for i in pt:
    if i in lower:
            ct+=lower[(lower.find(i)+key)%26]
        
    elif i in upper:
            ct += upper[(upper.find(i)+key)%26]

    elif i == ' ':
            ct += ' '

print(ct)