# -*- coding: utf-8 -*-
"""Diffie_Hellman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MwZ2B6griBOkCmvvwnl9ZXQj8c2v01BO
"""

def diffie(g,a,b,p):
  a_generated=pow(g,a)%p
  b_generated=pow(g,b)%p

  shared_key_a=pow(b_generated,a)%p
  shared_key_b=pow(a_generated,b)%p

  if(shared_key_a==shared_key_b):
    print("Authentication successfull")
  else:
    print("Authentication Failed")


#P = 23, G = 9 ,a = 4, b = 3
diffie(9,4,3,23)

