# -*- coding: utf-8 -*-
"""ECB_final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luP7w2OrWWumQ68S9UpoWXQkHOzw_jeh
"""

# Add String here to Encrypt and Decrypt
plain = "stavan here"
ascii_chars = []
binary = []
encrypted = []
for char in plain:
 # Converting characters into ascii values
  ascii_chars.append(ord(char))
 # Converting ascii values into 16 bit binary
  grp_16 = bin(ord(char))[2:]
  binary.append(grp_16)
 
 # Taking t=1 for circular left shift
  text = grp_16[1:] + grp_16[0]
  if len(text)==6:
 # print("6: "+text)
    text = "0" + text
    encrypted.append(text)
  else:
    encrypted.append(text)
# Taking key to perform XOR with
key = 65
# Converting key into 16 but binary, we can take key which is 16 bit only
binary_key = bin(key)[2:]
print("Binary Key: " + binary_key)
print(f"Key Type: {type(binary_key)}")
print(ascii_chars)
print(binary)
print(encrypted)

# Applying XOR
msg = []
encrypt = []
for num in encrypted:
 xor = int(num, 2)^int(binary_key, 2)
 msg.append(xor)
 encrypt.append(chr(xor))
print(msg)
print(encrypt)
encrypted_text = ''.join(char for char in encrypt)
print(encrypted_text)

